In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
df = pd.read_csv(r"C:\Users\avanindra Bose\OneDrive\Desktop\Real State Project\Cleaned Datasets\gurgaon_properties_missing_value_imputation.csv")

In [4]:
df.head()

,property_type,society,sector,price,price_per_square_feet,bedRoom,bathroom,balcony,floorNum,agePossession,built_up_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,flat,rof aalayas,sector 102,0.45,6000.0,1,1,2,6.0,Relatively New,750.0,0,0,0,0,0,1,0
1,house,huda sector-56 gurgaon,sector 56,3.60,24845.0,5,5,3+,3.0,Moderately Old,1449.0,0,0,0,0,1,1,47
2,flat,parsvnath green ville,sector 48,2.50,12820.0,4,5,3,1.0,Moderately Old,2167.0,0,0,0,0,1,0,49
3,flat,emaar gurgaon greens,sector 102,1.35,8181.0,3,3,3,5.0,Relatively New,1315.0,0,1,0,0,0,1,119
4,flat,raheja sampada,sector 92,0.65,4744.0,3,2,3,6.0,Relatively New,1240.0,0,0,0,0,0,1,49

In [5]:
latlong = pd.read_csv(r"C:\Users\avanindra Bose\OneDrive\Desktop\Real State Project\Cleaned Datasets\latlong.csv")

In [6]:
latlong.head()

     sector             coordinates
0  sector 1  28.3663° N, 76.9456° E
1  sector 2  28.5095° N, 77.0320° E
2  sector 3  28.4909° N, 77.0176° E
3  sector 4  28.4738° N, 77.0107° E
4  sector 5  28.4794° N, 77.0176° E

In [7]:
latlong['latitude'] = latlong['coordinates'].str.split(',').str.get(0).str.split('°').str.get(0).astype('float')

In [8]:
latlong['longitude'] = latlong['coordinates'].str.split(',').str.get(1).str.split('°').str.get(0).astype('float')

In [9]:

latlong.head()

     sector             coordinates  latitude  longitude
0  sector 1  28.3663° N, 76.9456° E   28.3663    76.9456
1  sector 2  28.5095° N, 77.0320° E   28.5095    77.0320
2  sector 3  28.4909° N, 77.0176° E   28.4909    77.0176
3  sector 4  28.4738° N, 77.0107° E   28.4738    77.0107
4  sector 5  28.4794° N, 77.0176° E   28.4794    77.0176

In [10]:
new_df = df.merge(latlong, on='sector')

In [11]:
new_df.columns

Index(['property_type', 'society', 'sector', 'price', 'price_per_square_feet',
       'bedRoom', 'bathroom', 'balcony', 'floorNum', 'agePossession',
       'built_up_area', 'study room', 'servant room', 'store room',
       'pooja room', 'others', 'furnishing_type', 'luxury_score',
       'coordinates', 'latitude', 'longitude'],
      dtype='object')

In [12]:
group_df = new_df.groupby('sector').mean(numeric_only=True)[['price','price_per_square_feet','built_up_area','latitude','longitude']]

In [18]:
group_df[['price','price_per_square_feet','built_up_area']] = group_df[['price','price_per_square_feet','built_up_area']].round(2)

In [19]:
group_df

             price  price_per_square_feet  built_up_area  latitude  longitude
sector
gwal pahari   3.19                9585.89        3056.17   28.4484    77.0210
manesar       0.96                4607.84        2027.37   28.3515    76.9428
sector 1      1.86                8249.50        2327.83   28.3663    76.9456
sector 102    1.70               10603.72        1556.13   28.4750    76.9715
sector 103    1.50                7445.48        1865.43   28.4949    76.9845
...            ...                    ...            ...       ...        ...
sector 92     0.93                5928.06        1571.34   28.4079    76.9153
sector 93     0.85                8010.56        1017.00   28.4153    76.9326
sector 95     0.48                5602.00         995.98   28.4172    76.9081
sector 99     1.49                6797.75        1802.67   28.4640    76.9614
sector 99a    0.82                6257.13        1188.83   28.4561    76.9542

[104 rows x 5 columns]

In [20]:
fig = px.scatter_map(group_df, lat="latitude", lon="longitude", color="price_per_square_feet", size='built_up_area',
                  color_continuous_scale=px.colors.cyclical.IceFire, zoom=10,
                  text=group_df.index)
fig.show()

# Observations 
1. The Above Visualization will show average price per square feet , Price , Built Up Area for the entire sector.

In [21]:
new_df.to_csv('data_viz1.csv',index=False)