In [1]:
import pandas as pd 
import numpy as np

In [57]:
from sklearn.model_selection import KFold, cross_val_score , cross_validate
from sklearn.linear_model import LinearRegression ,Ridge,Lasso
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import ExtraTreesRegressor, AdaBoostRegressor
from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [6]:
df = pd.read_csv(r"C:\Users\avanindra Bose\OneDrive\Desktop\Real State Project\Cleaned Datasets\gurgaon_properties_post_feature_selection_v2.csv")

In [7]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [8]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [9]:
df['furnishing_type'] = df['furnishing_type'].replace({0.0:'unfurnished',1.0:'semifurnished',2.0:'furnished'})

In [32]:
df.sample(5)

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
743,house,sector 105,1.15,3.0,2.0,1,Moderately Old,3889.0,0.0,0.0,unfurnished,Low,Low Floor
913,flat,sector 92,0.95,4.0,3.0,2,New Property,1983.0,0.0,0.0,unfurnished,Low,High Floor
216,flat,sector 81,2.29,3.0,4.0,3+,Relatively New,1900.0,1.0,0.0,furnished,Medium,High Floor
3393,flat,sector 72,3.30,3.0,4.0,3+,New Property,2185.0,1.0,0.0,furnished,High,High Floor
1520,flat,sector 37d,1.08,3.0,3.0,3,Relatively New,1700.0,0.0,0.0,unfurnished,High,Mid Floor

In [11]:
X = df.drop(columns=['price'])
y = df['price']

In [12]:
y_transformed = np.log1p(y)

# Ordinal Encoding

In [33]:
num_col = ['bedRoom','bathroom','built_up_area','servant room' , 'store room']

In [34]:
cat_col = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

In [35]:
preprocess = ColumnTransformer(
    transformers= [
        ('num',StandardScaler(), num_col),
        ('cat' ,OrdinalEncoder() , cat_col)
    ] , 
    remainder="passthrough"
)

In [36]:
pipeline = Pipeline(
    [
        ('preprocess' , preprocess),
        ('estimator' , LinearRegression())
    ]
)

In [37]:
k_fold = KFold(n_splits=10 , shuffle=True , random_state=42)
scores = cross_val_score(pipeline,X,y_transformed,cv=k_fold , scoring='r2')

In [39]:
scores.mean()

np.float64(0.7363096633436828)

In [41]:
scores.std()

np.float64(0.03238005754429936)

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [43]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category'])])),
                ('estimator', LinearRegression())])

In [44]:
y_pred = pipeline.predict(X_test)

In [45]:
y_pred = np.expm1(y_pred)

In [46]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.9463822160089356

In [49]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocess),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [50]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor(),
    'KNN' : KNeighborsRegressor()
}

In [51]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [52]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [53]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.889488  0.504048
5       random forest  0.880289  0.536237
6         extra trees  0.868155  0.548131
7   gradient boosting  0.872611  0.575952
11                KNN  0.803658  0.668036
9                 mlp  0.813489  0.714517
4       decision tree  0.769772  0.733718
1                 svr  0.764201  0.847264
8            adaboost  0.763069  0.850916
2               ridge  0.736313  0.946339
0          linear_reg  0.736310  0.946382
3               LASSO  0.059434  1.528906

In [58]:
scoring = {
    "r2": "r2",
    "mae": "neg_mean_absolute_error"
}

In [59]:
k_fold = KFold(n_splits=10 , shuffle=True , random_state=42)
scores = cross_validate(pipeline,X,y_transformed,cv=k_fold , scoring=scoring)

In [61]:
print("Mean R2:", scores["test_r2"].mean())
print("Mean MAE:", -scores["test_mae"].mean())

Mean R2: 0.7363096633436828
Mean MAE: 0.21293592367164615

# One Hot Encoding

In [62]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_col),
        ('cat', OrdinalEncoder(), cat_col),
        ('cat1',OneHotEncoder(drop='first'),['sector','agePossession','furnishing_type'])
    ], 
    remainder='passthrough'
)

In [63]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [64]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [65]:
scores.mean()

np.float64(0.8546094810971422)

In [66]:
scores.std()

np.float64(0.015997422908695623)

In [67]:

X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [68]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first'),
                                                  ['sector', 'agePossession',
                                                   'furnishing_type'])])),
                ('regressor', LinearRegression())])

In [69]:
y_pred = pipeline.predict(X_test)

In [70]:

y_pred = np.expm1(y_pred)

In [71]:
mean_absolute_error(np.expm1(y_test),y_pred)

0.6497514315131458

In [72]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [73]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [74]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

c:\Users\avanindra Bose\OneDrive\Desktop\Real State Project\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:781: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [75]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [76]:
model_df.sort_values(['mae'])

                 name        r2       mae
6         extra trees  0.893706  0.460849
10            xgboost  0.895850  0.493456
5       random forest  0.890726  0.500973
7   gradient boosting  0.876369  0.566923
9                 mlp  0.871748  0.608029
0          linear_reg  0.854609  0.649751
2               ridge  0.854739  0.652915
4       decision tree  0.806764  0.700962
1                 svr  0.769741  0.834124
8            adaboost  0.754739  0.837752
3               LASSO  0.059434  1.528906

# Target Encoder

In [80]:
import category_encoders as ce

columns_to_encode = ['property_type','sector', 'balcony', 'agePossession', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [81]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [82]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [83]:
scores.mean(),scores.std()

(np.float64(0.8295219182255362), np.float64(0.018384463379122782))

In [84]:
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [85]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [86]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

In [87]:
model_df = pd.DataFrame(model_output, columns=['name','r2','mae'])

In [88]:
model_df.sort_values(['mae'])

                 name        r2       mae
10            xgboost  0.904798  0.447518
6         extra trees  0.902091  0.452926
5       random forest  0.900611  0.460506
7   gradient boosting  0.888958  0.508507
4       decision tree  0.826431  0.547384
9                 mlp  0.854207  0.583055
8            adaboost  0.815677  0.697422
0          linear_reg  0.829522  0.713011
2               ridge  0.829536  0.713523
1                 svr  0.782917  0.818851
3               LASSO  0.059434  1.528906

# Hence We can say that the best model for Our Dataset was XGBoost and Random Forest.

# HyperParameter Tuning Using Optuna

In [94]:
import optuna

c:\Users\avanindra Bose\OneDrive\Desktop\Real State Project\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [179]:
X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [180]:
columns_to_encode = ['property_type','balcony', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [181]:
def mae_original(y_true, y_pred):
    return mean_absolute_error(np.expm1(y_true), np.expm1(y_pred))

mae_scorer = make_scorer(mae_original, greater_is_better=False)

In [197]:
def objective(trial):
    params = {
        
    "objective": "reg:squarederror",
    "booster": "gbtree",  # safest choice for tabular
    "n_estimators": trial.suggest_int("n_estimators", 100, 5000),  # more trees = safer, especially with small learning_rate
    "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.5, log=True),  # controls step size
    "max_depth": trial.suggest_int("max_depth", 3, 12),  # tree complexity
    "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),  # min samples per leaf
    "subsample": trial.suggest_float("subsample", 0.7, 1.0),  # row sampling
    "colsample_bytree": trial.suggest_float("colsample_bytree", 0.7, 1.0),  # feature sampling
    "gamma": trial.suggest_float("gamma", 0, 5),  # split penalty
    "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 3.0, log=True),  # L1 regularization
    "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 3.0, log=True),  # L2 regularizatio

    }


    model = Pipeline([
        ('preprocessor', preprocessor),   
        ('regressor', XGBRegressor(**params, random_state=42, n_jobs=-1))
    ])

    model.fit(X_train,y_train)
    preds = model.predict(X_test)
    mae = mean_absolute_error(np.expm1(y_test) , np.expm1(preds))
    # r2 = r2_score(np.expm1(y_test),preds)

    return mae

In [205]:
study = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=300)  # Run 50 trials to find the best hyperparameters

[I 2025-09-05 01:23:56,954] A new study created in memory with name: no-name-7f8adad3-cba3-4f28-a197-7abd7060e84d
[I 2025-09-05 01:23:57,523] Trial 0 finished with value: 0.6133130060603683 and parameters: {'n_estimators': 3245, 'learning_rate': 0.16187286662927378, 'max_depth': 12, 'min_child_weight': 3, 'subsample': 0.9947802144649395, 'colsample_bytree': 0.9272626679215805, 'gamma': 3.4745574180926075, 'reg_alpha': 0.0013207744614442398, 'reg_lambda': 0.004904108250909164}. Best is trial 0 with value: 0.6133130060603683.
[I 2025-09-05 01:23:58,018] Trial 1 finished with value: 0.5981178457257449 and parameters: {'n_estimators': 2563, 'learning_rate': 0.3157165840669792, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8661740251529855, 'colsample_bytree': 0.8236910478024894, 'gamma': 2.7475512350550395, 'reg_alpha': 1.8798702536997316e-06, 'reg_lambda': 0.00028564247996054647}. Best is trial 1 with value: 0.5981178457257449.
[I 2025-09-05 01:23:58,211] Trial 2 finished with value: 0.5943593066100833 and parameters: {'n_estimators': 787, 'learning_rate': 0.05205529942464183, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.7206273522075242, 'colsample_bytree': 0.8449862684454132, 'gamma': 2.731844044660399, 'reg_alpha': 0.0003310139960601304, 'reg_lambda': 0.005150190738482801}. Best is trial 2 with value: 0.5943593066100833.
[I 2025-09-05 01:23:58,795] Trial 3 finished with value: 0.5905388492220062 and parameters: {'n_estimators': 2500, 'learning_rate': 0.027127680504267653, 'max_depth': 12, 'min_child_weight': 6, 'subsample': 0.9128993151135152, 'colsample_bytree': 0.8500470337092053, 'gamma': 2.4534150288777807, 'reg_alpha': 0.012801343509568963, 'reg_lambda': 1.109773984409911}. Best is trial 3 with value: 0.5905388492220062.
[I 2025-09-05 01:23:58,877] Trial 4 finished with value: 0.6007053064126338 and parameters: {'n_estimators': 182, 'learning_rate': 0.07931842619406314, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.9257478536921537, 'colsample_bytree': 0.7815035766381484, 'gamma': 3.321378531916706, 'reg_alpha': 0.00029785649505361924, 'reg_lambda': 0.2890413420899054}. Best is trial 3 with value: 0.5905388492220062.
[I 2025-09-05 01:23:59,303] Trial 5 finished with value: 0.4926575896592414 and parameters: {'n_estimators': 1292, 'learning_rate': 0.015244333232338255, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.9966840800887125, 'colsample_bytree': 0.8979714036111339, 'gamma': 0.09026164773134449, 'reg_alpha': 4.621390550682615e-05, 'reg_lambda': 0.0016751397795914977}. Best is trial 5 with value: 0.4926575896592414.
[I 2025-09-05 01:24:00,063] Trial 6 finished with value: 0.5588667380977448 and parameters: {'n_estimators': 3935, 'learning_rate': 0.012686961208465882, 'max_depth': 11, 'min_child_weight': 6, 'subsample': 0.7630432337091482, 'colsample_bytree': 0.9910147841693372, 'gamma': 0.9662846814922904, 'reg_alpha': 0.007991605544075986, 'reg_lambda': 5.541444776882343e-08}. Best is trial 5 with value: 0.4926575896592414.
[I 2025-09-05 01:24:00,180] Trial 7 finished with value: 0.6055423150485075 and parameters: {'n_estimators': 201, 'learning_rate': 0.11012701261096033, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9074858278798051, 'colsample_bytree': 0.7899017531185525, 'gamma': 3.399768668342608, 'reg_alpha': 7.431777997606547e-06, 'reg_lambda': 0.00030237779476868977}. Best is trial 5 with value: 0.4926575896592414.
[I 2025-09-05 01:24:00,299] Trial 8 finished with value: 0.6092642570447319 and parameters: {'n_estimators': 212, 'learning_rate': 0.06984307218653675, 'max_depth': 11, 'min_child_weight': 8, 'subsample': 0.8126366007084979, 'colsample_bytree': 0.7230864684712597, 'gamma': 3.4700897948194815, 'reg_alpha': 0.20493094096478406, 'reg_lambda': 3.0069967479067762e-06}. Best is trial 5 with value: 0.4926575896592414.
[I 2025-09-05 01:24:00,814] Trial 9 finished with value: 0.6029786941807314 and parameters: {'n_estimators': 2740, 'learning_rate': 0.4866091015823623, 'max_depth': 7, 'min_child_weight': 1, 'subsample': 0.7209313529867575, 'colsample_bytree': 0.7350126077841906, 'gamma': 2.1987058647383844, 'reg_alpha': 0.27615195562077177, 'reg_lambda': 0.004861104226179648}. Best is trial 5 with value: 0.4926575896592414.
[I 2025-09-05 01:24:01,365] Trial 10 finished with value: 0.4888467802880685 and parameters: {'n_estimators': 1676, 'learning_rate': 0.01359820679964902, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.9862172432853306, 'colsample_bytree': 0.9147696077749224, 'gamma': 0.08856282924772013, 'reg_alpha': 1.4199047941475028e-08, 'reg_lambda': 1.4732735352101518e-06}. Best is trial 10 with value: 0.4888467802880685.
[I 2025-09-05 01:24:01,876] Trial 11 finished with value: 0.52203721262064 and parameters: {'n_estimators': 1779, 'learning_rate': 0.011513561493862774, 'max_depth': 8, 'min_child_weight': 10, 'subsample': 0.9962067287797833, 'colsample_bytree': 0.9131801112017327, 'gamma': 0.2979593996505976, 'reg_alpha': 1.794429490565009e-08, 'reg_lambda': 1.2165937377228344e-06}. Best is trial 10 with value: 0.4888467802880685.
[I 2025-09-05 01:24:02,393] Trial 12 finished with value: 0.4832826456708412 and parameters: {'n_estimators': 1425, 'learning_rate': 0.025973158470893345, 'max_depth': 8, 'min_child_weight': 10, 'subsample': 0.9571212078622474, 'colsample_bytree': 0.9201099058453733, 'gamma': 0.017571162886014235, 'reg_alpha': 3.298373369219307e-08, 'reg_lambda': 1.2842504451665869e-05}. Best is trial 12 with value: 0.4832826456708412.
[I 2025-09-05 01:24:02,694] Trial 13 finished with value: 0.6296363819366434 and parameters: {'n_estimators': 1569, 'learning_rate': 0.028465837151387705, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.9530413981463028, 'colsample_bytree': 0.9851618366775159, 'gamma': 4.686987564971278, 'reg_alpha': 2.3164662225834115e-08, 'reg_lambda': 5.2853189058445735e-06}. Best is trial 12 with value: 0.4832826456708412.
[I 2025-09-05 01:24:03,637] Trial 14 finished with value: 0.5673549052381315 and parameters: {'n_estimators': 4965, 'learning_rate': 0.02611425713529051, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.8611633082011229, 'colsample_bytree': 0.9467715732212834, 'gamma': 1.3118185744701423, 'reg_alpha': 2.9728181375227684e-07, 'reg_lambda': 1.4157226111711463e-08}. Best is trial 12 with value: 0.4832826456708412.
[I 2025-09-05 01:24:04,029] Trial 15 finished with value: 0.5574736374339977 and parameters: {'n_estimators': 1952, 'learning_rate': 0.04017849241141411, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.9510449144795724, 'colsample_bytree': 0.8862175952691913, 'gamma': 0.9527558069706374, 'reg_alpha': 2.4864234253714293e-07, 'reg_lambda': 1.898032307934797e-05}. Best is trial 12 with value: 0.4832826456708412.
[I 2025-09-05 01:24:04,272] Trial 16 finished with value: 0.575569265777384 and parameters: {'n_estimators': 1039, 'learning_rate': 0.01991711656504666, 'max_depth': 7, 'min_child_weight': 10, 'subsample': 0.9585157404891598, 'colsample_bytree': 0.9637566024215988, 'gamma': 1.6448846122045864, 'reg_alpha': 1.0681041664736144e-08, 'reg_lambda': 2.355659076094575e-07}. Best is trial 12 with value: 0.4832826456708412.
[I 2025-09-05 01:24:04,770] Trial 17 finished with value: 0.5403603786607332 and parameters: {'n_estimators': 2118, 'learning_rate': 0.010708881782014335, 'max_depth': 10, 'min_child_weight': 9, 'subsample': 0.8285078771544446, 'colsample_bytree': 0.8779774720194553, 'gamma': 0.5740719414627727, 'reg_alpha': 2.1114255312854767e-07, 'reg_lambda': 4.1958024777819825e-05}. Best is trial 12 with value: 0.4832826456708412.
[I 2025-09-05 01:24:05,717] Trial 18 finished with value: 0.48245393663602876 and parameters: {'n_estimators': 3660, 'learning_rate': 0.018620403956541166, 'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.8923061732746372, 'colsample_bytree': 0.9394287535092161, 'gamma': 0.04724835171499032, 'reg_alpha': 4.4930535904383055e-06, 'reg_lambda': 2.1465895983140913e-07}. Best is trial 18 with value: 0.48245393663602876.
[I 2025-09-05 01:24:06,379] Trial 19 finished with value: 0.5761831915965395 and parameters: {'n_estimators': 3773, 'learning_rate': 0.0360290942974906, 'max_depth': 6, 'min_child_weight': 7, 'subsample': 0.8842100500745824, 'colsample_bytree': 0.9432885451674097, 'gamma': 1.8286518417579094, 'reg_alpha': 1.051484089528196e-05, 'reg_lambda': 1.6959428560451493e-07}. Best is trial 18 with value: 0.48245393663602876.
[I 2025-09-05 01:24:07,355] Trial 20 finished with value: 0.6351503765599804 and parameters: {'n_estimators': 4874, 'learning_rate': 0.020097682046789262, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.7913373990073991, 'colsample_bytree': 0.8639154657492027, 'gamma': 4.919826598916355, 'reg_alpha': 1.3480445152726235e-06, 'reg_lambda': 1.0060699781812452e-08}. Best is trial 18 with value: 0.48245393663602876.
[I 2025-09-05 01:24:08,669] Trial 21 finished with value: 0.474768751664336 and parameters: {'n_estimators': 3220, 'learning_rate': 0.017594882537917994, 'max_depth': 8, 'min_child_weight': 9, 'subsample': 0.9653415463261177, 'colsample_bytree': 0.9143595240873107, 'gamma': 0.005596664425783111, 'reg_alpha': 1.027043757544507e-07, 'reg_lambda': 8.026487289323348e-07}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:09,533] Trial 22 finished with value: 0.545365011091809 and parameters: {'n_estimators': 3603, 'learning_rate': 0.01986599816742938, 'max_depth': 6, 'min_child_weight': 9, 'subsample': 0.9368989455367697, 'colsample_bytree': 0.9471759411352099, 'gamma': 0.6473209466976007, 'reg_alpha': 9.475169029994399e-08, 'reg_lambda': 4.242151378502659e-07}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:10,452] Trial 23 finished with value: 0.539595729211547 and parameters: {'n_estimators': 4348, 'learning_rate': 0.040201657419445265, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.8955971912085299, 'colsample_bytree': 0.9729297836221709, 'gamma': 0.5660807309296424, 'reg_alpha': 3.311003879245896e-06, 'reg_lambda': 1.966106981376518e-05}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:11,199] Trial 24 finished with value: 0.560285888650414 and parameters: {'n_estimators': 3124, 'learning_rate': 0.017163617174246523, 'max_depth': 8, 'min_child_weight': 8, 'subsample': 0.9673808405277841, 'colsample_bytree': 0.9013583194817959, 'gamma': 1.1156047277455583, 'reg_alpha': 5.341928827312151e-05, 'reg_lambda': 5.919545389249551e-08}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:12,505] Trial 25 finished with value: 0.4794894259086641 and parameters: {'n_estimators': 4226, 'learning_rate': 0.05309867129663726, 'max_depth': 10, 'min_child_weight': 9, 'subsample': 0.8810138126978821, 'colsample_bytree': 0.9358452611410419, 'gamma': 0.038186229338361286, 'reg_alpha': 7.140708202801863e-07, 'reg_lambda': 7.265340229201423e-05}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:13,555] Trial 26 finished with value: 0.5389806391803859 and parameters: {'n_estimators': 4349, 'learning_rate': 0.12245938195313258, 'max_depth': 10, 'min_child_weight': 7, 'subsample': 0.8779626752848844, 'colsample_bytree': 0.9652464461257054, 'gamma': 0.4262023839527491, 'reg_alpha': 8.38002336941033e-07, 'reg_lambda': 6.527676542964702e-05}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:14,575] Trial 27 finished with value: 0.5750274860272091 and parameters: {'n_estimators': 4274, 'learning_rate': 0.06842942753954437, 'max_depth': 11, 'min_child_weight': 5, 'subsample': 0.8317211990634663, 'colsample_bytree': 0.9387842771397508, 'gamma': 1.3868049084114076, 'reg_alpha': 1.736116936892643e-05, 'reg_lambda': 0.10401901433129707}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:15,393] Trial 28 finished with value: 0.5479308680525644 and parameters: {'n_estimators': 3307, 'learning_rate': 0.052184437537912055, 'max_depth': 9, 'min_child_weight': 9, 'subsample': 0.8442716099803843, 'colsample_bytree': 0.8791599400523283, 'gamma': 0.8058379978215297, 'reg_alpha': 6.032675749090898e-07, 'reg_lambda': 5.531705775872313e-07}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:16,075] Trial 29 finished with value: 0.5777567139640974 and parameters: {'n_estimators': 3018, 'learning_rate': 0.19482670276039424, 'max_depth': 10, 'min_child_weight': 8, 'subsample': 0.9267885990684531, 'colsample_bytree': 0.998591932982912, 'gamma': 1.705679104904799, 'reg_alpha': 1.1836424602296222e-07, 'reg_lambda': 7.848793523939767e-08}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:16,842] Trial 30 finished with value: 0.6137829529752878 and parameters: {'n_estimators': 3530, 'learning_rate': 0.18162050241985653, 'max_depth': 12, 'min_child_weight': 2, 'subsample': 0.8977469944443747, 'colsample_bytree': 0.9266921715517402, 'gamma': 4.197729854196897, 'reg_alpha': 5.905487209492208e-05, 'reg_lambda': 6.371233242341549e-06}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:17,692] Trial 31 finished with value: 0.4842242987087172 and parameters: {'n_estimators': 4005, 'learning_rate': 0.030742182676168676, 'max_depth': 8, 'min_child_weight': 10, 'subsample': 0.9726247203339097, 'colsample_bytree': 0.9259165527935217, 'gamma': 0.02578476371649059, 'reg_alpha': 6.18051843567958e-08, 'reg_lambda': 0.000127751760563361}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:18,574] Trial 32 finished with value: 0.5233062990556788 and parameters: {'n_estimators': 4639, 'learning_rate': 0.022735329502040557, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.9449344596985859, 'colsample_bytree': 0.9083448947767416, 'gamma': 0.35333820583472664, 'reg_alpha': 3.34573144167842e-06, 'reg_lambda': 0.000873157789415567}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:19,098] Trial 33 finished with value: 0.5235957952659006 and parameters: {'n_estimators': 2760, 'learning_rate': 0.053036079019037397, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.873708682712448, 'colsample_bytree': 0.9581256168709877, 'gamma': 0.2869321055369787, 'reg_alpha': 4.94472829104628e-08, 'reg_lambda': 9.769718473674083e-06}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:19,749] Trial 34 finished with value: 0.4823385014195314 and parameters: {'n_estimators': 2359, 'learning_rate': 0.015747782555532327, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.9218172677982058, 'colsample_bytree': 0.8234940102348695, 'gamma': 0.025637725778467485, 'reg_alpha': 3.907564123937532e-07, 'reg_lambda': 2.9453096442704155e-06}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:20,370] Trial 35 finished with value: 0.5505939369010523 and parameters: {'n_estimators': 2271, 'learning_rate': 0.017875168143421438, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.9190200777050008, 'colsample_bytree': 0.8289208935916674, 'gamma': 0.7591892368780668, 'reg_alpha': 0.001772787604381552, 'reg_lambda': 2.35397774233188e-06}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:21,001] Trial 36 finished with value: 0.5622342781309673 and parameters: {'n_estimators': 3281, 'learning_rate': 0.01590208551623539, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.8590059140374869, 'colsample_bytree': 0.7859083560089465, 'gamma': 1.1621199468505607, 'reg_alpha': 9.764806330142408e-07, 'reg_lambda': 9.698508589370684e-07}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:21,690] Trial 37 finished with value: 0.5966678023204186 and parameters: {'n_estimators': 2412, 'learning_rate': 0.034714456898870955, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.894019456065895, 'colsample_bytree': 0.8019848107650345, 'gamma': 2.91179998600654, 'reg_alpha': 3.7608580166024217e-06, 'reg_lambda': 0.000283271298861094}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:22,402] Trial 38 finished with value: 0.5506411998315535 and parameters: {'n_estimators': 2932, 'learning_rate': 0.2535145607141141, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.9356383538035478, 'colsample_bytree': 0.8452142259805088, 'gamma': 0.3086601636442935, 'reg_alpha': 2.1173148208909113e-05, 'reg_lambda': 0.048052271520743046}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:23,245] Trial 39 finished with value: 0.6276029074141747 and parameters: {'n_estimators': 4118, 'learning_rate': 0.09968736216307068, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9166983993448448, 'colsample_bytree': 0.7573664450483941, 'gamma': 3.8169430306512107, 'reg_alpha': 2.7050003561369653, 'reg_lambda': 2.2495463761583684e-08}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:24,047] Trial 40 finished with value: 0.5553803042989911 and parameters: {'n_estimators': 3534, 'learning_rate': 0.010204227192961593, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.9077970708785091, 'colsample_bytree': 0.819741037763434, 'gamma': 0.8646065900549641, 'reg_alpha': 5.337322451474869e-07, 'reg_lambda': 1.7697902481422466e-07}. Best is trial 21 with value: 0.474768751664336.
[I 2025-09-05 01:24:24,756] Trial 41 finished with value: 0.4730923138883715 and parameters: {'n_estimators': 893, 'learning_rate': 0.02378919638020318, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.977505733748079, 'colsample_bytree': 0.8683610748957369, 'gamma': 0.004450128256754747, 'reg_alpha': 4.28162162511394e-08, 'reg_lambda': 2.8900921364288603e-05}. Best is trial 41 with value: 0.4730923138883715.
[I 2025-09-05 01:24:25,252] Trial 42 finished with value: 0.4791319651618789 and parameters: {'n_estimators': 801, 'learning_rate': 0.014010977733275386, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.9666610588550634, 'colsample_bytree': 0.8592644201793049, 'gamma': 0.010174140282752552, 'reg_alpha': 1.6969061457357083e-07, 'reg_lambda': 9.191320760373965e-05}. Best is trial 41 with value: 0.4730923138883715.
[I 2025-09-05 01:24:25,474] Trial 43 finished with value: 0.5336023464031863 and parameters: {'n_estimators': 572, 'learning_rate': 0.014299933256286097, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.9809102224621444, 'colsample_bytree': 0.8667596651931254, 'gamma': 0.4050789690302892, 'reg_alpha': 1.3538705444184452e-07, 'reg_lambda': 0.0006046355556585807}. Best is trial 41 with value: 0.4730923138883715.
[I 2025-09-05 01:24:25,726] Trial 44 finished with value: 0.5081840058368973 and parameters: {'n_estimators': 638, 'learning_rate': 0.014423897895185514, 'max_depth': 7, 'min_child_weight': 7, 'subsample': 0.9807822852866112, 'colsample_bytree': 0.8307373655472539, 'gamma': 0.20462833123219484, 'reg_alpha': 4.6073987740479874e-08, 'reg_lambda': 5.786647511392974e-05}. Best is trial 41 with value: 0.4730923138883715.
[I 2025-09-05 01:24:26,088] Trial 45 finished with value: 0.5422589001541567 and parameters: {'n_estimators': 982, 'learning_rate': 0.023341270079532964, 'max_depth': 11, 'min_child_weight': 8, 'subsample': 0.9678946849503552, 'colsample_bytree': 0.8595255220196995, 'gamma': 0.5767114086968249, 'reg_alpha': 3.402400875658709e-07, 'reg_lambda': 0.006782670720010901}. Best is trial 41 with value: 0.4730923138883715.
[I 2025-09-05 01:24:26,281] Trial 46 finished with value: 0.5895924302411649 and parameters: {'n_estimators': 450, 'learning_rate': 0.012939050668597619, 'max_depth': 9, 'min_child_weight': 9, 'subsample': 0.9936885225794467, 'colsample_bytree': 0.8980360120364171, 'gamma': 2.240792248593018, 'reg_alpha': 3.282931650034383e-08, 'reg_lambda': 0.00012468200474596494}. Best is trial 41 with value: 0.4730923138883715.

In [199]:
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.4327019562835264
Best hyperparameters: {'n_estimators': 2247, 'learning_rate': 0.029607581182756134, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.8776300145819186, 'colsample_bytree': 0.7140091435602947, 'gamma': 0.0014673093687880855, 'reg_alpha': 7.817104638830973e-06, 'reg_lambda': 1.1448017199516563e-07}

In [206]:
best_params = {
    "n_estimators": 2247,
    "learning_rate": 0.029607581182756134,
    "max_depth": 8,
    "min_child_weight": 1,
    "subsample": 0.8776300145819186,
    "colsample_bytree": 0.7140091435602947,
    "gamma": 0.0014673093687880855,
    "reg_alpha": 7.817104638830973e-06,
    "reg_lambda": 1.1448017199516563e-07,
    "random_state": 42,
    "n_jobs": -1
}

In [207]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

# Split hold-out test set
X_trainval, X_final_test, y_trainval, y_final_test = train_test_split(
    X, y_transformed, test_size=0.2, random_state=42
)

# Fit on training+validation
final_model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(**best_params))
])
final_model.fit(X_trainval, y_trainval)

# Predict on final test
y_pred_final = final_model.predict(X_final_test)

print("Hold-out R²:", r2_score(y_final_test, y_pred_final))
print("Hold-out MAE:", mean_absolute_error(np.expm1(y_final_test), np.expm1(y_pred_final)))

Hold-out R²: 0.920148633377009
Hold-out MAE: 0.4327019562835264

In [ ]:
def objective_rf(trial):
    params = {
        
    # number of trees (higher → stabler, but slower)
    "n_estimators": trial.suggest_int("n_estimators", 200, 5000, step=100),

    # maximum depth of trees (None = full growth, but usually overfits)
    "max_depth": trial.suggest_int("max_depth", 5, 30),

    # minimum samples required to split a node
    "min_samples_split": trial.suggest_int("min_samples_split", 2, 10),

    # minimum samples required at a leaf
    "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 5),

    # number of features to consider at each split
    "max_features": trial.suggest_categorical("max_features", ["sqrt", "log2", None]),

    # whether to use bootstrap sampling
    "bootstrap": trial.suggest_categorical("bootstrap", [True, False]),
}



    model = Pipeline([
        ('preprocessor', preprocessor),   
        ('regressor', RandomForestRegressor(**params, random_state=42, n_jobs=-1))
    ])

    model.fit(X_train,y_train)
    preds = model.predict(X_test)
    mae = mean_absolute_error(np.expm1(y_test) , np.expm1(preds))
    # r2 = r2_score(np.expm1(y_test),preds)

    return mae

In [ ]:
study = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective_rf, n_trials=300)

# Exporting the Model

In [208]:
columns_to_encode = ['property_type','balcony', 'furnishing_type', 'luxury_category', 'floor_category']

# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'built_up_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(), columns_to_encode),
        ('cat1',OneHotEncoder(drop='first',sparse_output=False),['agePossession']),
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ], 
    remainder='passthrough'
)

In [209]:
final_model = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(**best_params))
])

In [210]:
final_model.fit(X,y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'built_up_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat', OrdinalEncoder(),
                                                  ['property_type', 'balcony',
                                                   'furnishing_type',
                                                   'luxury_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['agePosse...
                              gamma=0.0014673093687880855, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None,
                              learning_rate=0.029607581182756134, max_bin=None,
                              max_cat_threshold=None, max_cat_to_onehot=None,
                              max_delta_step=None, max_depth=8, max_leaves=None,
                              min_child_weight=1, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=2247, n_jobs=-1,
                              num_parallel_tree=None, ...))])

In [211]:
import pickle

with open("final_xgb_pipeline.pkl", "wb") as f:
    pickle.dump(final_model, f)

In [212]:
with open('df.pkl', 'wb') as file:
    pickle.dump(X, file)

In [213]:
X

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,3.0,2.0,2,New Property,850.0,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,2.0,2.0,2,New Property,1226.0,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,2.0,2.0,1,New Property,1000.0,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,semifurnished,High,Mid Floor
4,flat,sector 102,2.0,2.0,1,Relatively New,582.0,0.0,1.0,unfurnished,High,Mid Floor
...,...,...,...,...,...,...,...,...,...,...,...,...
3549,flat,sector 84,2.0,2.0,1,Relatively New,532.0,0.0,0.0,unfurnished,Medium,Mid Floor
3550,house,sector 109,5.0,5.0,3+,Relatively New,6228.0,1.0,1.0,unfurnished,High,Low Floor
3551,flat,sector 2,1.0,1.0,1,Moderately Old,665.0,0.0,0.0,semifurnished,Medium,Mid Floor
3552,house,sector 43,5.0,6.0,3,Moderately Old,5490.0,1.0,1.0,unfurnished,Medium,Mid Floor
3553,flat,sector 68,3.0,3.0,3+,Relatively New,1845.0,0.0,0.0,semifurnished,Medium,High Floor

# Testing out the Model

In [214]:
X.columns

Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category'],
      dtype='object')

In [215]:
X.iloc[0].values

array(['flat', 'sector 36', np.float64(3.0), np.float64(2.0), '2',
       'New Property', np.float64(850.0), np.float64(0.0),
       np.float64(0.0), 'unfurnished', 'Low', 'Low Floor'], dtype=object)

In [219]:
data = [['house', 'sector 81', 2, 3, '3+', 'New Property', 1345, 0, 0, 'unfurnished', 'Low', 'Low Floor']]
columns = ['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'built_up_area', 'servant room', 'store room',
       'furnishing_type', 'luxury_category', 'floor_category']

one_df = pd.DataFrame(data, columns=columns)

one_df

,property_type,sector,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,house,sector 81,2,3,3+,New Property,1345,0,0,unfurnished,Low,Low Floor

In [220]:
np.expm1(final_model.predict(one_df))

array([1.3568053], dtype=float32)

In [221]:
X.dtypes

property_type       object
sector              object
bedRoom            float64
bathroom           float64
balcony             object
agePossession       object
built_up_area      float64
servant room       float64
store room         float64
furnishing_type     object
luxury_category     object
floor_category      object
dtype: object